import "@/styles/globals.css";
import { AppProps } from "next/app";
import Head from "next/head";
import { MantineProvider } from "@mantine/core";
import { Nunito } from '@next/font/google';

const secondaryFont = Nunito({ subsets: ['latin'] })

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Ashutosh Dash</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <style jsx global>{`
          h1,
          h2,
          h3,
          h4,
          h5,
          h6, span,p, a, div {
            font-family: ${secondaryFont.style.fontFamily}!important;
          }
        `}</style>
        <MantineProvider
          withGlobalStyles
          withNormalizeCSS
          theme={{
            colorScheme: "light",
          }}
        >
          <Component {...pageProps} />
        </MantineProvider>
      </main>
    </>
  );
}
