import "@/styles/globals.css";
import { AppProps } from "next/app";
import Head from "next/head";
import { MantineProvider } from "@mantine/core";
import { Nunito } from "@next/font/google";
import {PreviewImg} from "public/metaimg.png"
import {FaviconImg} from "public/favicon.ico"
const secondaryFont = Nunito({ subsets: ["latin"] });

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Ashutosh Dash</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="description"
          content="Ashutosh Dash, Frontend/UI Developer. Bringing life to sketches."
        />
        <meta name="author" content="Ashutosh Dash" />
        <meta
          name="keywords"
          content="ashu, ashutosh, ashutosh dash, developer, web developer, front end developer frontend developer, designer, ui developer"
        />
        <meta
          name="theme-color"
          media="(prefers-color-scheme: light)"
          content="#86efac"
        />
        <meta
          name="theme-color"
          media="(prefers-color-scheme: dark)"
          content="#7e22ce"
        />
        <meta name="robots" content="index,follow" />
        <meta name="Googlebot" content="index,follow" />
        <meta
          property="og:site_name"
          content="https://ashutoshdash.netlify.app/"
        />
        <meta property="og:title" content="Ashutosh Dash | Portfolio" />
        <meta
          property="og:description"
          content="Ashutosh Dash :: Frontend Developer|| React Developer || JavaScript Developer. Bringing life to sketches."
        />
        <meta
          property="og:image"
          content="./linkpreview.png"
        />
        <meta property="og:type" content="website" />
        <meta
          property="og:url"
          content="https://ashutoshdash.netlify.app"
        />
        <meta property="twitter:title" content="Ashutosh Dash | Portfolio" />
        <meta
          name="twitter:description"
          content="Ashutosh Dash, Frontend || UI || React || JavaScript Developer. Bringing life to sketches."
        />
        <meta name="twitter:image" content="./linkpreview.png" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="https://ashutoshdash.netlify.app/" />
        <meta name="application-name" content="Ashutosh Dash | Portfolio" />
        <meta
          name="apple-mobile-web-app-title"
          content="Ashutosh Dash | Portfolio"
        />
        <link rel="apple-touch-icon" href="./favicon.ico" />
        <meta
          name="summary"
          content="A minimalist portfolio made by Ashutosh Dash"
        />
      </Head>
      <main>
        <style jsx global>{`
          h1,
          h2,
          h3,
          h4,
          h5,
          h6,
          span,
          p,
          a,
          div {
            font-family: ${secondaryFont.style.fontFamily}!important;
          }
        `}</style>
        <MantineProvider
          withGlobalStyles
          withNormalizeCSS
          theme={{
            colorScheme: "light",
          }}
        >
          <Component {...pageProps} />
        </MantineProvider>
      </main>
    </>
  );
}
